In [1]:
import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis

import requests # library to handle requests

In [2]:
!pip install beautifulsoup4

Collecting beautifulsoup4
  Downloading https://files.pythonhosted.org/packages/e8/b5/7bb03a696f2c9b7af792a8f51b82974e51c268f15e925fc834876a4efa0b/beautifulsoup4-4.9.0-py3-none-any.whl (109kB)
     |████████████████████████████████| 112kB 8.3MB/s eta 0:00:01
Collecting soupsieve>1.2 (from beautifulsoup4)
  Downloading https://files.pythonhosted.org/packages/05/cf/ea245e52f55823f19992447b008bcbb7f78efc5960d77f6c34b5b45b36dd/soupsieve-2.0-py2.py3-none-any.whl
Installing collected packages: soupsieve, beautifulsoup4
Successfully installed beautifulsoup4-4.9.0 soupsieve-2.0

In [3]:
!pip install lxml

Collecting lxml
  Downloading https://files.pythonhosted.org/packages/dd/ba/a0e6866057fc0bbd17192925c1d63a3b85cf522965de9bc02364d08e5b84/lxml-4.5.0-cp36-cp36m-manylinux1_x86_64.whl (5.8MB)
     |████████████████████████████████| 5.8MB 7.5MB/s eta 0:00:01
Installing collected packages: lxml
Successfully installed lxml-4.5.0

In [4]:
from bs4 import BeautifulSoup
import requests

In [5]:
!wget -q -O 'Toronto_data.html' https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M

In [6]:
with open ('Toronto_data.html') as Thtml:
    Tsoup=BeautifulSoup(Thtml, 'lxml')

In [7]:
table=Tsoup.find('table')

In [8]:
table=Tsoup.tbody
len(table)

361

In [9]:
rows=Tsoup.table.tbody.find_all('tr')

In [10]:
data=[]
master=[]

In [11]:
for row in rows:
    for j in row.find_all('td'):
        data.append(j.text)
    master.append(data)
    data=[]

In [12]:
for row in master:
    for i,s in enumerate(row):
        row[i]=s.strip()

In [13]:
df=pd.DataFrame(master)

In [14]:
df.columns=['PostalCode', 'Borough', 'Neighborhood']

In [15]:
df1=df.replace('', np.nan)
df1.dropna(how='any', inplace=True)

In [16]:
df2=df1.reset_index(drop=True)

In [17]:
df2.replace(' / ', ' , ', regex=True, inplace=True)

In [18]:
dfsorted=df2.sort_values(by=['PostalCode'])

In [19]:
dfsorted.reset_index(drop=True)

    PostalCode      Borough                                       Neighborhood
0          M1B  Scarborough                                    Malvern , Rouge
1          M1C  Scarborough           Rouge Hill , Port Union , Highland Creek
2          M1E  Scarborough                Guildwood , Morningside , West Hill
3          M1G  Scarborough                                             Woburn
4          M1H  Scarborough                                          Cedarbrae
..         ...          ...                                                ...
98         M9N         York                                             Weston
99         M9P    Etobicoke                                          Westmount
100        M9R    Etobicoke  Kingsview Village , St. Phillips , Martin Grov...
101        M9V    Etobicoke  South Steeles , Silverstone , Humbergate , Jam...
102        M9W    Etobicoke                                          Northwest

[103 rows x 3 columns]

In [20]:
ll=pd.read_csv('Geospatial_Coordinates.csv')

In [21]:
ll.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [22]:
ll[['Latitude', 'Longitude']]

      Latitude  Longitude
0    43.806686 -79.194353
1    43.784535 -79.160497
2    43.763573 -79.188711
3    43.770992 -79.216917
4    43.773136 -79.239476
..         ...        ...
98   43.706876 -79.518188
99   43.696319 -79.532242
100  43.688905 -79.554724
101  43.739416 -79.588437
102  43.706748 -79.594054

[103 rows x 2 columns]

In [23]:
dfinal=dfsorted.join(ll[['Latitude', 'Longitude']] )

In [24]:
dfinal.reset_index(drop=True, inplace=True)

In [25]:
dfinal.head(5)

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern , Rouge",43.727929,-79.262029
1,M1C,Scarborough,"Rouge Hill , Port Union , Highland Creek",43.794200,-79.262029
2,M1E,Scarborough,"Guildwood , Morningside , West Hill",43.778517,-79.346556
3,M1G,Scarborough,Woburn,43.770120,-79.408493
4,M1H,Scarborough,Cedarbrae,43.745906,-79.352188

In [85]:
x=dfinal[dfinal.Borough.str.contains('Toronto')]

In [87]:
dfToronto=x.reset_index(drop=True)

In [88]:
dfToronto

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M4E,East Toronto,The Beaches,43.786947,-79.385975
1,M4K,East Toronto,"The Danforth West , Riverdale",43.679557,-79.352188
2,M4L,East Toronto,"India Bazaar , The Beaches West",43.704324,-79.388790
3,M4M,East Toronto,Studio District,43.657162,-79.378937
4,M4N,Central Toronto,Lawrence Park,43.648198,-79.379817
5,M4P,Central Toronto,Davisville North,43.653206,-79.400049
6,M4R,Central Toronto,North Toronto West,43.693781,-79.428191
7,M4S,Central Toronto,Davisville,43.713756,-79.490074
8,M4T,Central Toronto,"Moore Park , Summerhill East",43.648960,-79.456325
9,M4V,Central Toronto,"Summerhill West , Rathnelly , South Hill , For...",43.636966,-79.615819
10,M4W,Downtown Toronto,Rosedale,43.636258,-79.498509
11,M4X,Downtown Toronto,"St. James Town , Cabbagetown",43.756303,-79.565963
12,M4Y,Downtown Toronto,Church and Wellesley,43.696319,-79.532242
13,M5A,Downtown Toronto,"Regent Park , Harbourfront",43.763573,-79.188711
14,M5B,Downtown Toronto,"Garden District, Ryerson",43.692657,-79.264848
15,M5C,Downtown Toronto,St. James Town,43.799525,-79.318389
16,M5E,Downtown Toronto,Berczy Park,43.757490,-79.374714
17,M5G,Downtown Toronto,Central Bay Street,43.782736,-79.442259
18,M5H,Downtown Toronto,"Richmond , Adelaide , King",43.737473,-79.464763
19,M5J,Downtown Toronto,"Harbourfront East , Union Station , Toronto Is...",43.695344,-79.318389
20,M5K,Downtown Toronto,"Toronto Dominion Centre , Design Exchange",43.668999,-79.315572
21,M5L,Downtown Toronto,"Commerce Court , Victoria Hotel",43.689574,-79.383160
22,M5N,Central Toronto,Roselawn,43.733283,-79.419750
23,M5P,Central Toronto,Forest Hill North & West,43.628947,-79.394420
24,M5R,Central Toronto,"The Annex , North Midtown , Yorkville",43.689026,-79.453512
25,M5S,Downtown Toronto,"University of Toronto , Harbord",43.691116,-79.476013
26,M5T,Downtown Toronto,"Kensington Market , Chinatown , Grange Park",43.651571,-79.484450
27,M5V,Downtown Toronto,"CN Tower , King and Spadina , Railway Lands , ...",43.662744,-79.321558
28,M5W,Downtown Toronto,Stn A PO Boxes,43.628841,-79.520999
29,M5X,Downtown Toronto,"First Canadian Place , Underground city",43.724766,-79.532242
30,M6G,Downtown Toronto,Christie,43.753259,-79.329656
31,M6H,West Toronto,"Dufferin , Dovercourt Village",43.739015,-79.506944
32,M6J,West Toronto,"Little Portugal , Trinity",43.676357,-79.293031
33,M6K,West Toronto,"Brockton , Parkdale Village , Exhibition Place",43.659526,-79.340923
34,M6P,West Toronto,"High Park , The Junction South",43.646435,-79.374846
35,M6R,West Toronto,"Parkdale , Roncesvalles",43.669542,-79.422564
36,M6S,West Toronto,"Runnymede , Swansea",43.673185,-79.487262
37,M7A,Downtown Toronto,"Queen's Park , Ontario Provincial Government",43.773136,-79.239476
38,M7Y,East Toronto,Business reply mail Processing CentrE,43.688905,-79.554724

In [90]:
dfToronto.to_csv('dfToronto.csv', encoding='utf-8')